site_name: Tradebanq Design Revamp Plan
site_url: 
pages:
- [index.md, Home]
- [goals.md, Goals]
- [meetings.md, Meetings]
- [analysis.md, Analysis]
- [home.md, Analysis - Home]
- [listing.md, Analysis - Listing]
- [details.md, Analysis - Details]
theme: readthedocs
